---
- name: Create Projects dir
  file: path=~/Projects state=directory mode=0700

- name: Create Applications dir
  file: path=~/Applications state=directory mode=0700

- name: Create bin dir
  file: path=~/Applications/bin state=directory mode=0700

- name: Write scripts
  copy: src={{ item }} dest=~/Applications/bin/{{ item }} mode=0700
  with_items:
    - pw
    - work

- name: Write scripts (Arch)
  copy: src=canary dest=~/Applications/bin/canary mode=0700
  when: ansible_os_family == 'Archlinux'

- name: Write scripts 2 (Arch)
  template: src=chromium-daily.j2 dest=~/Applications/bin/chromium-daily mode=0700
  when: ansible_os_family == 'Archlinux'
