---
- name: Install vim (OS X)
  homebrew: name={{ item }} state=present
  with_items:
    - vim
    - cmake
  when: ansible_os_family == 'Darwin'

- name: Install vim (Arch)
  pacman: name=vim state=present
  when: ansible_os_family == 'Archlinux'

- name: Create dirs
  file: path=~/{{ item }} state=directory
  with_items:
    - .vim
    - .vim/autoload
    - .vim/undodir

- name: Download plug.vim
  get_url: url=https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim dest=~/.vim/autoload/plug.vim force=yes

- name: Write plug.vim
  copy: src=plug.vim dest=~/.vim/plug.vim

- name: Write vimrc
  copy: src=vimrc dest=~/.vimrc
